---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgButZbAP8zsyCFaqHJqTABZiteomhXnENy61SS9yvWjK88AJ53BojLk65TyV5qlae0QEntiWJI12lQe/iSS/PA4C1CoQG+X8Iki461E+UU37hG5raKqNtC47TjNEJfqMfv65IuSkDKRWOtidf3byXEy8FnTliT1K/R0oCqYCRqYg3oWq3ZF3m7FwQP1eXSDCoux54XjsmqOjlV3Piy2C2n936lqBnN87tqzUz3GdStdLns80NdcPJ2tHeET4oC/FDqj29ZhiJwhqIBPsRg58s3nu+VMsTfCSmGLh8j98d6OEAoVuOd5xh86nR4XpWG/yVA99Lvwp9RIehl+1mk43f2tDJh/sLnpFhgcHZE11dYE7Y80USxKlFOEn84Ajb9Ajra4nAIOHL8oNxdyhCPReT5VgmjER0QrhyG4E+TqX6gjb39ZBR19l3z3yRDtRKcfIVxlDd4+iBgm1lXVRs5HRK3EXvr+CZBPH2epxl9W620ewC1PeeAqXBYYYYHgO8fyY70RdW9s4is5g7cCof3aFhjiVceHePKBRCnXbKZYsj68Ba0ms08mXcUSx7oeJgTblQkpMNXjibfCjItajb5knSxJ4WQ+GJf1oCTEdWyBzw+6RUalJn3rouvlV/of+PE0gz7P/Ahz+HNn4l7/yuEJPPYMkp/5KAeUYNjouLioc5iqXRZP7TQzatRQUQonEPJbVI1vbjQt0Q==
    admin-user: AgBioSWUqHVhWur3hSrU4bV5as/VJi+it8YiVUNwIm+qp4HzvHxTgQZ4GBaC4+N/H6oQjw4eE+4PWcYYyeBBx9CNAMFI0HtsvnEf4rCCyAkI6pAuMiFFm59wHH6tOVefX6DfNOIDY9sqABFK8znT07U2+DbC8nD25FfBxBtv3/6P4luxumZhGVw/O7bZU9Y6gTNc7RmjM2zS9LLf4VFSf7VfpQ5x0WOULACPkLyW9DER/YJSLLOoY1fIxauQpgDmLtEAtk+BNugPeq3nb2olWxwkDqyZD3yCrW2VvRdduY9MWWcWruB0lJqnkS78xn7lXOqwuXSXJDba4IWT3jAiVlzuzFndSmx97hCan9U02FOZ8pf5xzYFYWjo4UHQB/wqJ/eZcckiOoob/QhlYKjA+bzmo97bxbwA9JYtgkkaos0fcf1BR2qc1zwMhW59KMtIfmZvz5hpNi0mi7eUVlF9YikiajaeOR5yghIpLI4VnxPYkRkxwNK3BjIM55lVNum273vgHkl16EujrS2x7K4n3QnvLk6sUDoFs/NIcZT4N9i7mSjpEKuWTe3lWSohEv1HTMq54gclnePMGeCPISl4JU8QGtsbtMZmC6H54DKYQguPeCY5dYs1zNVFjqVhOiPyEz8al0puGGTkfqdb+LiH6sOrs6TEPvb4/m6dFGBayxfKPjUDk3+u8ggkdzdDSH2QyT3Gt5D9rg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
