apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    password: AgBbshJ0Ql20jeY8ALCGuqs5JG1ZbsDn3CZZmJpa5SECeUimDINi6+UPmvEmEyi9gwB3iSy6bS+oCxDB8P3iHKx0Grubd+Gw8lzu3w1860wET7VdC7IuZ9MT8rp7CEaKMoQeDtF0HDvZ6JE4RziQMwo0e+pRadSNd/kfxWrA0VYgaLoFDmHSor0zvqFDnpmMmNcv6WBS5qVFymLmKDf32apNI+tCNsmN0sRtb88bP7Lu319wbbey2VD15spC4vlXdhv6eAP/dBkH9ADEYokLgNAgdsg1zW2Ru8GR4/ZnfuadduiOwW+/b9CO9HqgLxKZjuJA/PNNNNJB4FsPBT11Vq/U0W3BH4tEpA6IxeUGF6Vox+EF3iKVtGAockA9ZRqWSCwvYEQE10OCKQ6XjYHVqMDap9UqH7zx/OoLlpdwYUrbKwb8cjK8ukJa4oEdSVyXM33TlnS6Mi1m79iIg4rwoSlYzMmXJYeg6xHnFi7Jp88/74NjtZkwNN+xPY42RaGlWZS/SSbC+yjYvW6XrOGfW5+hZL0QWBLOeYe7n+SGfmMP+G78y/VOp26FQsI6Vn+HNUBGfaAcx042G7jD4vLITX/jrltDcseMOK90/hOSTHnEaTxolMh9KFJOCs8NWjxxhq0EiLGqodcCGAJPkl5s5ExgMl/x5NYK/PeDFSNEtTFcZKMlp2Vc9g9BJj9Rp8B9gucdJVMNVw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
