apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: kibana-transport
  namespace: logging
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kibana
  namespace: logging
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kibana.dubrovskih.ru`)
      kind: Rule
      services:
        - name: kibana-kb-http
          port: 5601
          scheme: https
          serversTransport: kibana-transport
  tls:
    secretName: kibana-tls
