apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sish
  namespace: sish
  labels:
    app.kubernetes.io/name: sish
spec:
  ingressClassName: traefik
  rules:
    - host: "*.tunnel.dubrovskih.ru"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sish-http
                port:
                  number: 8080
    - host: "sish.dubrovskih.ru"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sish-http
                port:
                  number: 8080
