apiVersion: v1
kind: Service
metadata:
  name: sish-ssh
  namespace: sish
  labels:
    app.kubernetes.io/name: sish
spec:
  type: NodePort
  ports:
    - name: ssh
      port: 2222
      targetPort: 2222
      nodePort: 32222
      protocol: TCP
  selector:
    app.kubernetes.io/name: sish
---
apiVersion: v1
kind: Service
metadata:
  name: sish-http
  namespace: sish
  labels:
    app.kubernetes.io/name: sish
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: sish
