---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgCUmd3Qo1/RRgnwBtc6KT98rATQhVUmcVNdeFSMANlU2n+/7XQj2NoOyR8QBZecg7OX+T3PibU04nJXQJ89cpop4d+OD2hf87QiL0yGODiyGRBJpfHNdJCSWw59bOkfTDW5ngEE47DE8eQn7okaKgzujaR/MN+Tq7AAIcOrsV+ZnEPOCsyfpl7UC4F7U6bMk5R0Abmlc1W9MH3rLmLmwcufQy71AT1yXr2gDSOyKipLcFD4DRB6zIN4MSbtk9KIiGht/hTcrp2za5oCBu2fJbqZki9cyoDSXRDhIk6tH9/neYBdoyemjg0P3ckFeUsAtJoa8x+JLc+K94bu21nfKpi0h2z8WVlXoqQuPsCPWe6C/2LzikV/lD0Wt82Z/YulWUG48mgI+69EbgfG0AljIm+6bvu3tnT+lWmjzGP5ZRlgU6zfWsWvPwjN1FkcZn3h3Ypzchw9ExVxCdXjqMHW17q0M+9VI5c2xvqj4XqCVRFNxl19PqzsKOg/3ikypCyg0Xc305S5lO1X5xwr8W+8RmAzVsAEp2VycUxWIL2T2B+26UKDaHh3W26dxZ+hQBtEbIyp958e4qnJp7W6d6nDfaAMUKGVf8DzrvHuqYU2UZ6MK7COBRFEbP4naw8enzd56mHVHUAGgdWFlVjBKSoLAZsXOrrb3FRHDgzOhApGimWIGJ+79/lKoAKxr5pQJlxqZB5eN2xDK0R6WgqTAm+ojeu97EmXdLNpxU3PoHNVGcjG2nM0V40WV4WTykMcfhHq
  template:
    metadata:
      name: alertmanager-telegram
      namespace: monitoring
