---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgBIXTPaTHky2YOB7SEdcom+jkmCKzlrfOhbN1I125CtUdlje5kYk6DwLIvFAZRNv9I4GLY1pdjwmCU/eTdkMabE/E0HRfsDoSMqoqXiWpDwvEuDtWeE2hrPD9sIT8YuU0u5fY1RzTPZHjwKt/LtxN/XV6cEXHer0qy+7wZopbnNKlwlFxvviEqc2vJW5Q51CLYZFBDw6DnB83X6BBRM/rTJSY6TVHm18BF5eMXFKgNRlwCn6+q1raxVYF/7WmKEBupcd7MC5f7hkM9xNVbFeLRNdijHP0A4dKxMfOULx63+m2BlJ7dSV0d5qboCrB6cl4PtwXrKde/ct1Oib0+dRCc+IGgHy/TrSJHM0pHEXNLxC1Cl+jWz5aNOR3fpjPfVYAXiE1Bjht2rRuc2UJ3XFLvKlZihcwU4JAQ/SEQy0s4OGDn5C2phOtY7fGHoVfo98yReBRG2FuGVRH+T0T6+hrnbPvWnolIcK8rsXPgGX1tEqKaiqsukuu4oa0PXhiYbvYgvaQn1fxekf3b2A6Sz+nwzNH9iNjqvvp5KZa3QeZH/cFvrKcEsJLCuA3yU/s5ybfj4QwaFU1G1B2lamynRoSzTa/CrR2REjeqJTiYWyXdxHkt5C1KPud0mbKaIY47uRwtXVed5t5oAroHOwehgbZYJpToC7cZw8ZE4RJl0Bx0y03tWVDKxPE9o0qrUg26BFRXuugZv5GftImGJwQenKUy6Jesna+PyKDhGQJ8yplo+4EKJah/YfBSoHYwF1BzZ
  template:
    metadata:
      name: alertmanager-telegram
      namespace: monitoring
    type: Opaque
