apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webdav-ingress
  namespace: webdav
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: webdav-stripprefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: k8s.ru.tuna.am
      http:
        paths:
          - path: /webdav
            pathType: Prefix
            backend:
              service:
                name: webdav
                port:
                  number: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: webdav
spec:
  stripPrefix:
    prefixes:
      - /webdav
