apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webdav-ingress
  namespace: webdav
spec:
  ingressClassName: traefik
  rules:
    - host: webdav.dubrovskih.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webdav
                port:
                  number: 80
