apiVersion: v1
kind: Service
metadata:
  name: webdav
  namespace: webdav
spec:
  selector:
    app: webdav
  ports:
    - name: webdav
      port: 80
      targetPort: 8080
    - name: admin
      port: 8081
      targetPort: 8081
