apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headscale-tls
  namespace: headscale
spec:
  secretName: headscale-tls
  dnsNames:
    - headscale.dubrovskih.ru
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headscale
  namespace: headscale
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`headscale.dubrovskih.ru`)
      kind: Rule
      services:
        - name: headscale
          port: 8080
  tls:
    secretName: headscale-tls
