apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: landing
  namespace: landing
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dubrovskih.ru`)
      kind: Rule
      services:
        - name: landing
          port: 80
  tls:
    secretName: landing-tls
